"""Add mobile enterprise support

Revision ID: 68f108684a94
Revises: 001_initial
Create Date: 2026-05-30 22:01:27.230191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f108684a94'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('biometric_public_key', sa.Text(), nullable=True),
    sa.Column('device_name', sa.Text(), nullable=True),
    sa.Column('last_active', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['access_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('law_user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_law_user_devices_device_id'), ['device_id'], unique=True)

    with op.batch_alter_table('access_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_auth_sessions_refresh_token'), ['refresh_token'], unique=True)

    with op.batch_alter_table('law_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_correspondences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_hearings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_judgments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_legal_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_limitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_offices', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'trial'"))

    with op.batch_alter_table('law_parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_pleadings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_power_of_attorney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('law_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_transactions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_timesheets', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_tasks', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_power_of_attorney', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_pleadings', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_parties', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_offices', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'trial'"))

    with op.batch_alter_table('law_notes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_limitations', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_legal_references', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_judgments', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_hearings', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_expenses', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_executions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_documents', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_correspondences', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_clients', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_refresh_token'))
        batch_op.drop_column('refresh_token')

    with op.batch_alter_table('access_profiles', schema=None) as batch_op:
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('law_user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_law_user_devices_device_id'))

    op.drop_table('law_user_devices')
    # ### end Alembic commands ###
